// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-x7g809893zAszKy0RQEHr_z9CDyve8',
    appId: '1:415904468257:web:1f0c3831c89f723eb0c260',
    messagingSenderId: '415904468257',
    projectId: 'cosworkstore',
    authDomain: 'cosworkstore.firebaseapp.com',
    storageBucket: 'cosworkstore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL851GtwV0yIq0ismq9I51dP6h-ArF1Uc',
    appId: '1:415904468257:android:0f863c4ec7a80487b0c260',
    messagingSenderId: '415904468257',
    projectId: 'cosworkstore',
    storageBucket: 'cosworkstore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSBiy7cicJo7MQBZsvoVRZJACND-r58M',
    appId: '1:415904468257:ios:339daa0d90370849b0c260',
    messagingSenderId: '415904468257',
    projectId: 'cosworkstore',
    storageBucket: 'cosworkstore.appspot.com',
    androidClientId: '415904468257-p4pmn0l66kgh112gagprkna5595u7a0c.apps.googleusercontent.com',
    iosClientId: '415904468257-61sekt4v0mlqqjvbicriooo2kbvvce34.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosWorkStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiSBiy7cicJo7MQBZsvoVRZJACND-r58M',
    appId: '1:415904468257:ios:339daa0d90370849b0c260',
    messagingSenderId: '415904468257',
    projectId: 'cosworkstore',
    storageBucket: 'cosworkstore.appspot.com',
    androidClientId: '415904468257-p4pmn0l66kgh112gagprkna5595u7a0c.apps.googleusercontent.com',
    iosClientId: '415904468257-61sekt4v0mlqqjvbicriooo2kbvvce34.apps.googleusercontent.com',
    iosBundleId: 'com.example.cosWorkStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC-x7g809893zAszKy0RQEHr_z9CDyve8',
    appId: '1:415904468257:web:9c305d7afad738d7b0c260',
    messagingSenderId: '415904468257',
    projectId: 'cosworkstore',
    authDomain: 'cosworkstore.firebaseapp.com',
    storageBucket: 'cosworkstore.appspot.com',
  );

}